In [1]:
import sys
!{sys.executable} -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)


In [3]:
import numpy as np
import math

In [4]:
a = np.array([1, 2, 3])

a, a.ndim

(array([1, 2, 3]), 1)

In [8]:
b = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(b)
print(b.shape)

# rows x cols

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
c = np.zeros((2, 3))
d = np.ones((2, 3))

c, d

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [16]:
e = np.random.random((2, 3))

e

array([[0.8338093 , 0.61289704, 0.20988865],
       [0.75814419, 0.36424645, 0.64645073]])

In [30]:
g = np.arange(10, 51, 2)
g

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
f = np.arange(50, 9, -2)
f

In [39]:
h = np.linspace(0, 10, 20)
h

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [44]:
a = np.arange(0 , 21, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [45]:
b = np.arange(0 , 21, 1)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [48]:
print(a + b)
print(a - b)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [50]:
f = np.array([0, -10, -5, -15, 0, -40])

celsius = (f - 32) * 5/9

celsius

array([-17.77777778, -23.33333333, -20.55555556, -26.11111111,
       -17.77777778, -40.        ])

In [51]:
celsius > -20

array([ True, False, False, False,  True, False])

In [52]:
celsius % 2 == 0

array([False, False, False, False, False,  True])

In [53]:
a*b

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [68]:
a = np.array([[1, 2,] ,[3, 4,]])
b = np.random.random((2, 6))

ValueError: operands could not be broadcast together with shapes (2,2) (2,6) 

In [69]:
a @ b

array([[1.27620754, 1.26503961, 1.22718828, 0.72177944, 1.30595553,
        0.89708409],
       [2.91973125, 2.57983293, 3.08460607, 1.51155029, 3.19548195,
        2.03545652]])